version: "3.9"

services:
  rediscache:
    image: redis
    volumes:
      - ./data/redis:/data/redis
  db:
    image: biarms/mysql:5.7
    environment: 
      - MYSQL_DATABASE=databasename
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3306:3306"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  web:
    build: 
        context: ..
        dockerfile: docker/Dockerfile
    ports:
      - "8001:80"
    volumes:
        - ../:/code:delegated
        - ../src:/code/src
        - ../.env:/code/.env
    depends_on:
        - db
    links:
      - rediscache
